### ISSUE TITLE
出现了错误

### ISSUE THREAD

**Issue by fuqiang03** [kuoruan/openwrt-upx#1]
18.06 glibc2.26 4.14内核
![20200808203122](https://user-images.githubusercontent.com/26851715/89710499-40a43500-d9b6-11ea-837a-bfd6ad11a1a2.png)

**Comment by kuoruan** [comment]
错误信息中没有看出是 upx 的代码出错了

**Comment by fuqiang03** [comment]
新版的貌似对 内核或者gcc不兼容

**Comment by fuqiang03** [comment]
现在已经继续使用老版本的了  编译的内核是4.14 gcc 7.3

**Comment by fuqiang03** [comment]
![image](https://user-images.githubusercontent.com/26851715/106988555-096ae100-67ab-11eb-90cf-a84519407d0b.png)
官方master主库出错

**Comment by fuqiang03** [comment]
@kuoruan 新版本依旧如此 使用master gcc10.3  x86
![image](https://user-images.githubusercontent.com/26851715/117830544-511b7000-b2a6-11eb-8fc3-82d2fd5903b2.png)
去upx的issues 没有找到类似的问题

**Comment by kuoruan** [comment]
https://github.com/kuoruan/openwrt-v2ray/actions/runs/801273170

我的所有架构的编译在 gcc 8.4 都没出错，你遇到这问题只有等 snapshot 到 gcc 10 之后看会不会遇到

**Comment by kuoruan** [comment]
而且你这截图上报的错，也不是 upx 源码上的错误啊，都是从 toolchain 上报出来的

**Comment by fuqiang03** [comment]
嗯嗯 我在尝试下 别的 办法   看着确实是像工具链报错

**Comment by fuqiang03** [comment]
![image](https://user-images.githubusercontent.com/26851715/117835026-3e0a9f00-b2aa-11eb-9502-0260ec515dbe.png)
以前的版本却可以成功
@kuoruan

**Comment by fuqiang03** [comment]
@kuoruan 
![QQ截图20210513235240](https://user-images.githubusercontent.com/26851715/118151584-5c0d0680-b446-11eb-876c-9122ba4d3b1e.png)
尝试了下 不知道这样会有什么影响

**Comment by kuoruan** [comment]
`staging_dir/toolchain-x86_64_gcc-10.3.0_musl/include/fortify/stdlib.h` 55 行，`NULL` 改为 `nullptr` 即可

**Comment by fuqiang03** [comment]
谢谢
