### ISSUE TITLE
UPX 4.0 => arm64会出现 “Illegal instruction”

### ISSUE THREAD

**Issue by v03413** [kuoruan/openwrt-upx#6]
前辈您好，感谢您为此包制作而付出的努力。😀  
---  

最近在使用本包压缩自写的Golang程序时，发现成功压缩之后，在arm64(软路由 r2s)平台，会出现报错`Illegal instruction`；
经过大量时间排查，发现这可能是upx自身问题，见 https://github.com/upx/upx/issues/534 ；当前为了依旧能够使用压缩，我用的是老版本   
https://github.com/kuoruan/openwrt-upx/blob/3f51247c84b654ead7baae9be35aeec55376d7e9/upx/Makefile   

提issue 只是作提醒记录，希望upx如果修复此问题后，前辈也跟进更新，谢谢🙏。

**Comment by kuoruan** [comment]
先试试看最新版能不能用，这个 issue 关闭了。如果有问题再开
