### ISSUE TITLE
压缩效果一般

### ISSUE THREAD

**Issue by osmboy** [kuoruan/openwrt-upx#8]

**Comment by osmboy** [comment]
1， 原先openwrt自己产生的bin包大小
![image](https://user-images.githubusercontent.com/20849756/212871508-602e1728-c465-4f18-a307-6b40d2f0f1e6.png)
2， 使用该库openwrt-upx之后的效果
![image](https://user-images.githubusercontent.com/20849756/212871793-23294191-e4e1-4eac-b0e4-7fe0e3f5777f.png)
几乎没有改变

**Comment by kuoruan** [comment]
这个主要还是压缩比较大的 ipk 的，具体压缩大小因包而异
